# CXX = g++
# CXXSDL = $(shell sdl2-config --cflags)
# LDSDL = $(shell sdl2-config --libs)
# CXXFLAGS = -Wall -c -std=c++11 $(CXXSDL)
# LDFLAGS = $(LDSDL) -lSDL2_image
# BIN_DIR = bin/

# all: load-texture

# load-texture: load-texture.o Game.o TextureManager.o
# 	$(CXX) $^ -o $(BIN_DIR)$@ $(LDFLAGS)

# %.o: %.cpp
# 	$(CXX) $(CXXFLAGS) $(INCLUDE) $^ -o $@

# clean:
# 	rm *.o && rm $(BIN_DIR)*

#OBJS specifies which files to compile as part of the project
OBJS = src\Game.cpp src\TextureManager.cpp src\load-texture.cpp

#CC specifies which compiler we're using
CC = g++

#INCLUDE_PATHS specifies the additional include paths we'll need
INCLUDE_PATHS = -IC:\TDM-GCC-64\include\SDL2

#LIBRARY_PATHS specifies the additional library paths we'll need
LIBRARY_PATHS = -LC:\TDM-GCC-64\lib

#COMPILER_FLAGS specifies the additional compilation options we're using
# -w suppresses all warnings
# -Wl,-subsystem,windows gets rid of the console window
COMPILER_FLAGS = -w -Wl,-subsystem,windows

#LINKER_FLAGS specifies the libraries we're linking against
LINKER_FLAGS = -lmingw32 -lSDL2main -lSDL2

#OBJ_NAME specifies the name of our exectuable
OBJ_NAME = bin\Debug\main

#This is the target that compiles our executable
all : $(OBJS)
	$(CC) $(OBJS) $(INCLUDE_PATHS) $(LIBRARY_PATHS) $(COMPILER_FLAGS) $(LINKER_FLAGS) -o $(OBJ_NAME)
